param(
  [Parameter(Mandatory = $true)]
  [string]$SourceRoot
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

$repoRoot = Split-Path -Parent $PSScriptRoot
$expectedCommit = (Get-Content (Join-Path $repoRoot 'ENGINE_SOURCE_REVISION') -Raw).Trim()
$productVersion = (Get-Content (Join-Path $repoRoot 'VERSION') -Raw).Trim()
$sourceRootResolved = (Resolve-Path $SourceRoot).Path

$actualCommit = (& git -C $sourceRootResolved rev-parse HEAD).Trim()
if ($LASTEXITCODE -ne 0 -or $actualCommit -ne $expectedCommit) {
  throw "Refusing to rewrite updater source in an unpinned checkout. Expected $expectedCommit; found $actualCommit"
}
if ($productVersion -notmatch '^0\.[1-9]\d*\.\d+$') {
  throw "Ghosium product VERSION must use the 0.x.y line; found '$productVersion'."
}

$buildPath = Join-Path $sourceRootResolved 'chrome/browser/ui/webui/help/BUILD.gn'
$basicUpdaterPath = Join-Path $sourceRootResolved 'chrome/browser/ui/webui/help/version_updater_basic.cc'
$ghosiumUpdaterPath = Join-Path $sourceRootResolved 'chrome/browser/ui/webui/help/version_updater_ghosium_win.cc'

foreach ($required in @($buildPath, $basicUpdaterPath)) {
  if (!(Test-Path $required -PathType Leaf)) {
    throw "Pinned Chromium updater layout changed; expected file missing: $required"
  }
}

$oldBuildBlock = @'
    } else {
      sources = [ "version_updater_basic.cc" ]
    }
'@
$newBuildBlock = @'
    } else {
      sources = [ "version_updater_ghosium_win.cc" ]
      deps += [
        "//chrome/browser:browser_process",
        "//chrome/browser/net",
        "//crypto",
        "//net",
        "//services/network/public/cpp",
        "//url",
      ]
    }
'@

$buildText = [IO.File]::ReadAllText($buildPath)
if ($buildText.Contains($oldBuildBlock)) {
  $buildText = $buildText.Replace($oldBuildBlock, $newBuildBlock)
  [IO.File]::WriteAllText($buildPath, $buildText, [Text.UTF8Encoding]::new($false))
} elseif (!$buildText.Contains($newBuildBlock)) {
  throw 'Pinned Chromium help/BUILD.gn changed; unable to install the Ghosium Windows VersionUpdater target.'
}

$updaterSource = @'
// Copyright 2026 Brendigo
// Ghosium Browser native Windows update integration.
//
// This source is generated by the Ghosium source transformation. It deliberately
// uses Chromium's browser network stack, verifies the downloaded Setup hash and
// Authenticode publisher, and launches the same Setup package in /UPDATE mode.
// No standalone maintenance helper executable is created.

#include "chrome/browser/ui/webui/help/version_updater.h"

#include <algorithm>
#include <array>
#include <cstdint>
#include <memory>
#include <optional>
#include <string>
#include <utility>
#include <vector>

#include "base/command_line.h"
#include "base/files/file.h"
#include "base/files/file_path.h"
#include "base/files/file_util.h"
#include "base/functional/bind.h"
#include "base/json/json_reader.h"
#include "base/memory/weak_ptr.h"
#include "base/process/launch.h"
#include "base/process/process.h"
#include "base/strings/string_number_conversions.h"
#include "base/strings/string_util.h"
#include "base/version.h"
#include "base/win/trust_util.h"
#include "chrome/browser/browser_process.h"
#include "chrome/browser/net/system_network_context_manager.h"
#include "crypto/hash.h"
#include "net/base/load_flags.h"
#include "net/base/net_errors.h"
#include "net/traffic_annotation/network_traffic_annotation.h"
#include "services/network/public/cpp/resource_request.h"
#include "services/network/public/cpp/simple_url_loader.h"
#include "services/network/public/mojom/fetch_api.mojom.h"
#include "url/gurl.h"

namespace {

constexpr char kGhosiumCurrentProductVersion[] = "__GHOSIUM_PRODUCT_VERSION__";
constexpr char kGhosiumUpdateManifestUrl[] =
    "https://updates.ghosium.com/windows/stable.json";
constexpr char kGhosiumUpdateHost[] = "updates.ghosium.com";
constexpr int64_t kMaxGhosiumUpdateBytes = 512LL * 1024LL * 1024LL;
constexpr size_t kMaxManifestBytes = 64 * 1024;

bool IsAllowedUpdateUrl(const GURL& url, bool require_setup_filename) {
  if (!url.is_valid() || !url.SchemeIs("https") || url.has_username() ||
      url.has_password() || url.has_ref() || url.has_query() ||
      url.host_piece() != kGhosiumUpdateHost) {
    return false;
  }

  if (require_setup_filename &&
      !base::EndsWith(url.path_piece(), "/Ghosium-Browser-Setup.exe",
                      base::CompareCase::SENSITIVE)) {
    return false;
  }
  return true;
}

VersionUpdater::Status NetworkFailureStatus(int net_error) {
  switch (net_error) {
    case net::ERR_INTERNET_DISCONNECTED:
    case net::ERR_NETWORK_CHANGED:
    case net::ERR_NAME_NOT_RESOLVED:
      return VersionUpdater::FAILED_OFFLINE;
    default:
      return VersionUpdater::FAILED_HTTP;
  }
}

std::unique_ptr<network::SimpleURLLoader> CreateUpdateLoader(const GURL& url) {
  auto request = std::make_unique<network::ResourceRequest>();
  request->url = url;
  request->method = "GET";
  request->credentials_mode = network::mojom::CredentialsMode::kOmit;
  request->load_flags = net::LOAD_BYPASS_CACHE | net::LOAD_DISABLE_CACHE;

  auto traffic_annotation = net::DefineNetworkTrafficAnnotation(
      "ghosium_browser_update", R"(
        semantics {
          sender: "Ghosium Browser Update"
          description:
            "Checks the Brendigo-owned Ghosium update endpoint and downloads "
            "a newer Ghosium Browser Setup package when the user checks for "
            "updates from the browser About page."
          trigger:
            "The user opens About Ghosium Browser, which invokes the browser "
            "update check."
          data:
            "No account identifier, browsing history, search query, cookie, "
            "or profile data is sent. The HTTPS request itself exposes normal "
            "network metadata such as the client IP address to the server."
          destination: WEBSITE
          internal {
            contacts {
              email: "security@ghosium.com"
            }
          }
          user_data {
            type: NONE
          }
          last_reviewed: "2026-09-08"
        }
        policy {
          cookies_allowed: NO
          setting:
            "The update check is initiated from About Ghosium Browser."
          policy_exception_justification:
            "Ghosium requires a first-party update channel to deliver browser "
            "security fixes."
        })");

  return network::SimpleURLLoader::Create(std::move(request),
                                           traffic_annotation);
}

class VersionUpdaterGhosiumWin : public VersionUpdater {
 public:
  VersionUpdaterGhosiumWin() = default;
  VersionUpdaterGhosiumWin(const VersionUpdaterGhosiumWin&) = delete;
  VersionUpdaterGhosiumWin& operator=(const VersionUpdaterGhosiumWin&) = delete;
  ~VersionUpdaterGhosiumWin() override = default;

  void CheckForUpdate(StatusCallback callback, PromoteCallback) override {
    manifest_loader_.reset();
    setup_loader_.reset();
    weak_factory_.InvalidateWeakPtrs();
    CleanupDownloadedSetup();

    callback_ = std::move(callback);
    available_version_.clear();
    expected_sha256_.clear();
    expected_size_ = 0;
    setup_url_ = GURL();

    callback_.Run(CHECKING, 0, false, false, std::string(), 0,
                  std::u16string());

    const GURL manifest_url(kGhosiumUpdateManifestUrl);
    if (!IsAllowedUpdateUrl(manifest_url, false)) {
      Fail(FAILED, u"The Ghosium update endpoint is invalid.");
      return;
    }

    manifest_loader_ = CreateUpdateLoader(manifest_url);
    manifest_loader_->DownloadToString(
        g_browser_process->system_network_context_manager()
            ->GetURLLoaderFactory(),
        base::BindOnce(&VersionUpdaterGhosiumWin::OnManifestDownloaded,
                       weak_factory_.GetWeakPtr()),
        kMaxManifestBytes);
  }

 private:
  void OnManifestDownloaded(std::optional<std::string> body) {
    const int net_error = manifest_loader_ ? manifest_loader_->NetError()
                                           : net::ERR_FAILED;
    const GURL final_url = manifest_loader_ ? manifest_loader_->GetFinalURL()
                                            : GURL();
    manifest_loader_.reset();

    if (net_error != net::OK || !body.has_value()) {
      Fail(NetworkFailureStatus(net_error),
           u"Ghosium could not reach the update service.");
      return;
    }
    if (!IsAllowedUpdateUrl(final_url, false)) {
      Fail(FAILED_HTTP,
           u"The Ghosium update service redirected to an untrusted location.");
      return;
    }

    std::optional<base::Value> parsed = base::JSONReader::Read(*body);
    if (!parsed.has_value() || !parsed->is_dict()) {
      Fail(FAILED, u"The Ghosium update manifest is invalid.");
      return;
    }

    const base::Value::Dict& manifest = parsed->GetDict();
    const std::optional<int> schema = manifest.FindInt("schema");
    const std::optional<bool> enabled = manifest.FindBool("enabled");
    const std::string* product = manifest.FindString("product");
    const std::string* platform = manifest.FindString("platform");
    const std::string* channel = manifest.FindString("channel");

    if (!schema.has_value() || *schema != 1 || !enabled.has_value() ||
        !product || *product != "Ghosium Browser" || !platform ||
        *platform != "windows" || !channel || *channel != "stable") {
      Fail(FAILED, u"The Ghosium update manifest failed validation.");
      return;
    }

    if (!*enabled) {
      callback_.Run(UPDATED, 0, false, false, std::string(), 0,
                    std::u16string());
      return;
    }

    const std::string* version_text = manifest.FindString("version");
    const std::string* setup_url_text = manifest.FindString("url");
    const std::string* sha256_text = manifest.FindString("sha256");
    const std::optional<int> size_value = manifest.FindInt("size");
    if (!version_text || !setup_url_text || !sha256_text ||
        !size_value.has_value()) {
      Fail(FAILED, u"The Ghosium update manifest is incomplete.");
      return;
    }

    const base::Version current_version(kGhosiumCurrentProductVersion);
    const base::Version available_version(*version_text);
    if (!current_version.IsValid() || !available_version.IsValid()) {
      Fail(FAILED, u"The Ghosium update version is invalid.");
      return;
    }
    if (available_version.CompareTo(current_version) <= 0) {
      callback_.Run(UPDATED, 0, false, false, std::string(), 0,
                    std::u16string());
      return;
    }

    setup_url_ = GURL(*setup_url_text);
    if (!IsAllowedUpdateUrl(setup_url_, true)) {
      Fail(FAILED,
           u"The Ghosium update package URL is outside the trusted update host.");
      return;
    }

    std::vector<uint8_t> expected_hash_bytes;
    if (sha256_text->size() != crypto::hash::kSha256Size * 2 ||
        !base::HexStringToBytes(*sha256_text, &expected_hash_bytes) ||
        expected_hash_bytes.size() != crypto::hash::kSha256Size) {
      Fail(FAILED, u"The Ghosium update package hash is invalid.");
      return;
    }

    if (*size_value <= 0 ||
        static_cast<int64_t>(*size_value) > kMaxGhosiumUpdateBytes) {
      Fail(FAILED, u"The Ghosium update package size is invalid.");
      return;
    }

    available_version_ = *version_text;
    expected_sha256_ = *sha256_text;
    expected_size_ = *size_value;

    base::FilePath temp_dir;
    if (!base::GetTempDir(&temp_dir)) {
      Fail(FAILED_DOWNLOAD,
           u"Ghosium could not access the Windows temporary directory.");
      return;
    }
    update_dir_ = temp_dir.Append(FILE_PATH_LITERAL("Brendigo"))
                      .Append(FILE_PATH_LITERAL("Ghosium Browser Update"));
    setup_path_ = update_dir_.Append(
        FILE_PATH_LITERAL("Ghosium-Browser-Setup.exe"));
    if (!base::CreateDirectory(update_dir_)) {
      Fail(FAILED_DOWNLOAD,
           u"Ghosium could not prepare the update directory.");
      return;
    }
    base::DeleteFile(setup_path_);

    callback_.Run(UPDATING, 0, false, false, available_version_,
                  expected_size_, std::u16string());

    setup_loader_ = CreateUpdateLoader(setup_url_);
    setup_loader_->SetOnDownloadProgressCallback(base::BindRepeating(
        &VersionUpdaterGhosiumWin::OnDownloadProgress,
        weak_factory_.GetWeakPtr()));
    setup_loader_->DownloadToFile(
        g_browser_process->system_network_context_manager()
            ->GetURLLoaderFactory(),
        base::BindOnce(&VersionUpdaterGhosiumWin::OnSetupDownloaded,
                       weak_factory_.GetWeakPtr()),
        setup_path_, expected_size_);
  }

  void OnDownloadProgress(uint64_t current) {
    if (expected_size_ <= 0 || !callback_) {
      return;
    }
    const uint64_t capped =
        std::min<uint64_t>(current, static_cast<uint64_t>(expected_size_));
    const int progress = static_cast<int>(
        std::min<uint64_t>(99, (capped * 100) /
                                   static_cast<uint64_t>(expected_size_)));
    callback_.Run(UPDATING, progress, false, false, available_version_,
                  expected_size_, std::u16string());
  }

  void OnSetupDownloaded(base::FilePath downloaded_path) {
    const int net_error = setup_loader_ ? setup_loader_->NetError()
                                        : net::ERR_FAILED;
    const GURL final_url = setup_loader_ ? setup_loader_->GetFinalURL() : GURL();
    setup_loader_.reset();

    if (net_error != net::OK || downloaded_path.empty()) {
      Fail(NetworkFailureStatus(net_error),
           u"Ghosium could not download the update package.");
      return;
    }
    if (!IsAllowedUpdateUrl(final_url, true)) {
      Fail(FAILED_DOWNLOAD,
           u"The Ghosium update download redirected to an untrusted location.");
      return;
    }
    if (downloaded_path != setup_path_) {
      Fail(FAILED_DOWNLOAD,
           u"The Ghosium update package was written to an unexpected path.");
      return;
    }

    const std::optional<int64_t> actual_size = base::GetFileSize(setup_path_);
    if (!actual_size.has_value() || *actual_size != expected_size_) {
      Fail(FAILED_DOWNLOAD,
           u"The Ghosium update package size did not match the release metadata.");
      return;
    }

    base::File setup_file(setup_path_,
                          base::File::FLAG_OPEN | base::File::FLAG_READ);
    std::array<uint8_t, crypto::hash::kSha256Size> digest{};
    if (!setup_file.IsValid() ||
        !crypto::hash::HashFile(crypto::hash::kSha256, &setup_file, digest)) {
      Fail(FAILED_DOWNLOAD,
           u"Ghosium could not verify the downloaded update package.");
      return;
    }

    const std::string actual_sha256 = base::HexEncode(digest);
    if (!base::EqualsCaseInsensitiveASCII(actual_sha256, expected_sha256_)) {
      Fail(FAILED_DOWNLOAD,
           u"The Ghosium update package failed SHA-256 verification.");
      return;
    }

    // Force Authenticode validation because Ghosium is built from the
    // unbranded Chromium configuration. The downloaded Setup must have a valid
    // trusted signature and the same publisher subject as the signed running
    // Ghosium Browser executable before it can be launched.
    if (!base::win::IsBinaryTrusted(setup_path_, true,
                                    true /* force_verify_in_dev_builds */)) {
      Fail(FAILED_DOWNLOAD,
           u"The Ghosium update package failed publisher verification.");
      return;
    }

    callback_.Run(UPDATING, 100, false, false, available_version_,
                  expected_size_, std::u16string());

    base::CommandLine setup_command(setup_path_);
    // /S must precede custom NSIS switches so .onInit already sees silent mode.
    setup_command.AppendArgNative(L"/S");
    setup_command.AppendArgNative(L"/UPDATE");
    setup_command.AppendArgNative(L"/DELETESELF");

    base::Process process =
        base::LaunchProcess(setup_command, base::LaunchOptions());
    if (!process.IsValid()) {
      Fail(FAILED,
           u"Ghosium verified the update but could not start the Setup package.");
      return;
    }

    // The Setup process stops Ghosium, replaces the application payload,
    // refreshes its installed maintenance copy, then removes the temporary
    // browser-downloaded Setup through that same maintenance package.
    setup_path_.clear();
    update_dir_.clear();
    callback_.Run(NEARLY_UPDATED, 100, false, false, available_version_,
                  expected_size_, std::u16string());
  }

  void CleanupDownloadedSetup() {
    if (!setup_path_.empty()) {
      base::DeleteFile(setup_path_);
    }
    if (!update_dir_.empty()) {
      base::DeletePathRecursively(update_dir_);
    }
    setup_path_.clear();
    update_dir_.clear();
  }

  void Fail(Status status, std::u16string message) {
    manifest_loader_.reset();
    setup_loader_.reset();
    CleanupDownloadedSetup();
    if (callback_) {
      callback_.Run(status, 0, false, false, available_version_,
                    expected_size_, message);
    }
  }

  StatusCallback callback_;
  std::unique_ptr<network::SimpleURLLoader> manifest_loader_;
  std::unique_ptr<network::SimpleURLLoader> setup_loader_;
  std::string available_version_;
  std::string expected_sha256_;
  int64_t expected_size_ = 0;
  GURL setup_url_;
  base::FilePath update_dir_;
  base::FilePath setup_path_;
  base::WeakPtrFactory<VersionUpdaterGhosiumWin> weak_factory_{this};
};

}  // namespace

std::unique_ptr<VersionUpdater> VersionUpdater::Create(
    content::WebContents* web_contents) {
  return std::make_unique<VersionUpdaterGhosiumWin>();
}
'@
$updaterSource = $updaterSource.Replace('__GHOSIUM_PRODUCT_VERSION__', $productVersion)
[IO.File]::WriteAllText($ghosiumUpdaterPath, $updaterSource, [Text.UTF8Encoding]::new($false))

$verifyBuild = [IO.File]::ReadAllText($buildPath)
$verifySource = [IO.File]::ReadAllText($ghosiumUpdaterPath)
foreach ($requiredBuild in @(
  'sources = [ "version_updater_ghosium_win.cc" ]',
  '"//chrome/browser:browser_process"',
  '"//chrome/browser/net"',
  '"//crypto"',
  '"//services/network/public/cpp"'
)) {
  if (!$verifyBuild.Contains($requiredBuild)) {
    throw "Ghosium updater BUILD integration failed: missing $requiredBuild"
  }
}
foreach ($requiredSource in @(
  '#include <algorithm>',
  'https://updates.ghosium.com/windows/stable.json',
  "kGhosiumCurrentProductVersion[] = `"$productVersion`"",
  'CredentialsMode::kOmit',
  'crypto::hash::HashFile',
  'base::win::IsBinaryTrusted',
  'true /* force_verify_in_dev_builds */',
  'Ghosium-Browser-Setup.exe',
  'AppendArgNative(L"/S")',
  'AppendArgNative(L"/UPDATE")',
  'AppendArgNative(L"/DELETESELF")'
)) {
  if (!$verifySource.Contains($requiredSource)) {
    throw "Ghosium updater source verification failed: missing $requiredSource"
  }
}
foreach ($forbidden in @('update.exe', 'updater.exe', 'powershell.exe', 'cmd.exe', 'curl.exe')) {
  if ($verifySource -match [regex]::Escape($forbidden)) {
    throw "Ghosium updater source contains forbidden maintenance dependency: $forbidden"
  }
}

$thirdPartyChanges = & git -C $sourceRootResolved status --porcelain=v1 -- third_party
if ($LASTEXITCODE -ne 0) {
  throw 'Unable to verify third_party source state after updater rewrite.'
}
if ($thirdPartyChanges) {
  throw 'Ghosium updater rewrite modified third_party sources; refusing to continue.'
}

Write-Host "Ghosium native Windows VersionUpdater installed for product version $productVersion."
